###############################################################
#  Generated by:      Cadence Innovus 18.10-p002_1
#  OS:                Linux x86_64(Host ID ee-mill1)
#  Generated on:      Thu Oct  2 16:18:12 2025
#  Design:            lfsr4
#  Command:           create_ccopt_clock_tree_spec -file REPORTS/ctsspec.tcl
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# Clocks present at pin clk
#   clk (period 1.000ns) in timing_config CONSTRAINTS([OUTPUTS/lfsr4_synth.sdc])
create_ccopt_clock_tree -name clk -source clk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner corner_typ -early -clock_tree clk 0.050

set_ccopt_property target_max_trans_sdc -delay_corner corner_typ -late -clock_tree clk 0.050
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk 1

# Skew group to balance non generated clock:clk in timing_config:CONSTRAINTS (sdc OUTPUTS/lfsr4_synth.sdc)
create_ccopt_skew_group -name clk/CONSTRAINTS -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/CONSTRAINTS true
set_ccopt_property extracted_from_clock_name -skew_group clk/CONSTRAINTS clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/CONSTRAINTS CONSTRAINTS
set_ccopt_property extracted_from_delay_corners -skew_group clk/CONSTRAINTS {corner_typ corner_typ}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

