
// Generated by Cadence Genus(TM) Synthesis Solution 18.10-p003_1
// Generated on: Oct  8 2025 12:32:49 BST (Oct  8 2025 11:32:49 UTC)

// Verification Directory fv/lfsr4 

module lfsr4(clk, rst, data_out);
  input clk, rst;
  output [3:0] data_out;
  wire clk, rst;
  wire [3:0] data_out;
  wire n_0, n_1;
  DFSNQD1BWP7T \sreg_reg[1] (.SDN (n_0), .CP (clk), .D (n_1), .Q
       (data_out[0]));
  CKXOR2D0BWP7T g16__8780(.A1 (data_out[2]), .A2 (data_out[3]), .Z
       (n_1));
  DFCNQD1BWP7T \sreg_reg[4] (.CDN (n_0), .CP (clk), .D (data_out[2]),
       .Q (data_out[3]));
  DFCNQD1BWP7T \sreg_reg[3] (.CDN (n_0), .CP (clk), .D (data_out[1]),
       .Q (data_out[2]));
  DFCNQD1BWP7T \sreg_reg[2] (.CDN (n_0), .CP (clk), .D (data_out[0]),
       .Q (data_out[1]));
  INVD0BWP7T g20(.I (rst), .ZN (n_0));
endmodule

